name: Windows Build
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_mingw'

      - name: Configure and Build
        shell: pwsh
        run: |
          # 1. Ищем, где реально лежит g++.exe
          $Gxx = (Get-ChildItem -Path D:\a\ -Filter g++.exe -Recurse | Where-Object { $_.FullName -like "*mingw*" } | Select-Object -First 1).FullName
          $MingwBin = Split-Path $Gxx
          $Make = Join-Path $MingwBin "mingw32-make.exe"
          
          Write-Host "Real Compiler Path: $Gxx"
          Write-Host "Real Make Path: $Make"

          # 2. Изолируем PATH
          $env:PATH = "$MingwBin;${{ env.Qt6_DIR }}\bin;C:\Program Files\CMake\bin;C:\Windows\system32"

          # 3. Сборка
          cmake -B build -G "MinGW Makefiles" . `
            -DCMAKE_CXX_COMPILER="$Gxx" `
            -DCMAKE_MAKE_PROGRAM="$Make" `
            -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" `
            -DCMAKE_BUILD_TYPE=Release
            
          cmake --build build --config Release

      - name: Prepare Deployment
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          mkdir dist
          $exeFile = Get-ChildItem -Path build/*.exe -Recurse | Select-Object -First 1
          if ($exeFile) {
            Copy-Item $exeFile.FullName -Destination dist/
            $env:PATH = "${{ env.Qt6_DIR }}\bin;" + $env:PATH
            windeployqt --dir dist "dist/$($exeFile.Name)"
          }
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PathFinder-Windows-Package
          path: dist/
