name: Windows Build
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_mingw'

      - name: Setup MinGW
        uses: egor-tensin/setup-gcc@v1
        with:
          platform: x64

      - name: Configure and Build
        run: |
          # Собираем из текущей папки (.), так как CMakeLists.txt здесь
          cmake -B build -G "MinGW Makefiles" .
          cmake --build build --config Release

      - name: Prepare Deployment
        run: |
          mkdir dist
          # Копируем бинарник (проверь, чтобы имя совпало с тем, что в CMakeLists)
          cp build/GuiV.exe dist/
          # Собираем DLL-ки
          windeployqt --dir dist dist/GuiV.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PathFinder-Windows-Package
          path: dist/
