name: Windows Build
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_mingw'

      - name: Configure and Build
        shell: bash
        run: |
          # Добавляем путь к MinGW, который идет в комплекте с Qt
          export PATH="$Qt6_Dir/../../Tools/mingw1120_64/bin:$PATH"
          
          cmake -B build -G "MinGW Makefiles" .
          cmake --build build --config Release

      - name: Prepare Deployment
        shell: pwsh
        run: |
          mkdir dist
          # Копируем exe (ищем в папке build или build/Release)
          Get-ChildItem -Path build/*.exe -Recurse | Copy-Item -Destination dist/
          
          # Запускаем windeployqt
          $exeFile = Get-ChildItem -Path dist/*.exe | Select-Object -First 1
          if ($exeFile) {
            windeployqt --dir dist $exeFile.FullName
          } else {
            Write-Error "EXE file not found in build directory!"
            exit 1
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PathFinder-Windows-Package
          path: dist/
