name: Windows Build
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_mingw'

      - name: Full Build and Deploy
        shell: pwsh
        run: |
          # 1. Настраиваем пути к родному MinGW от Qt
          $QtDir = "${{ env.Qt6_DIR }}"
          $MingwBin = "$QtDir\..\..\Tools\mingw1120_64\bin"
          $env:PATH = "$MingwBin;$QtDir\bin;$env:PATH"
          
          Write-Host "Using Compiler from: $MingwBin"
          g++ --version # Проверяем, что теперь 11.2.0
          
          # 2. Конфигурируем и собираем
          cmake -B build -G "MinGW Makefiles" . `
            -DCMAKE_CXX_COMPILER="$MingwBin\g++.exe" `
            -DCMAKE_C_COMPILER="$MingwBin\gcc.exe" `
            -DCMAKE_MAKE_PROGRAM="$MingwBin\mingw32-make.exe" `
            -DCMAKE_PREFIX_PATH="$QtDir" `
            -DCMAKE_BUILD_TYPE="Release"
            
          cmake --build build --config Release

          # 3. Подготовка папки с программой (Deploy)
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          New-Item -ItemType Directory -Path dist
          
          $exeFile = Get-ChildItem -Path build/*.exe -Recurse | Select-Object -First 1
          if ($exeFile) {
              Copy-Item $exeFile.FullName -Destination dist\
              Write-Host "Deploying: $($exeFile.Name)"
              
              # Запуск windeployqt
              windeployqt --dir dist "dist\$($exeFile.Name)"
          } else {
              Write-Error "EXE not found!"
              exit 1
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PathFinder-Windows-Package
          path: dist/
