name: Windows Build
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          arch: 'win64_mingw'

      - name: Install MinGW 11.2
        run: |
          choco install mingw --version=11.2.0 -y --no-progress

      - name: Full Build and Deploy
        shell: pwsh
        run: |
          # 1. Находим пути
          $MingwBin = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          $QtBin = "${{ env.Qt6_DIR }}\bin"
          
          # 2. ВОЗВРАЩАЕМ CMAKE В PATH (берем его из текущего PATH перед очисткой)
          $CmakePath = Get-Command cmake | Select-Object -ExpandProperty Source | Split-Path
          $env:PATH = "$MingwBin;$QtBin;$CmakePath;C:\Windows\system32;C:\Windows"
          
          Write-Host "Checking Compiler..."
          g++ --version # Ожидаем 11.2.0
          Write-Host "Checking CMake..."
          cmake --version
          
          # 3. Сборка
          cmake -B build -G "MinGW Makefiles" . `
            -DCMAKE_CXX_COMPILER="$MingwBin\g++.exe" `
            -DCMAKE_C_COMPILER="$MingwBin\gcc.exe" `
            -DCMAKE_MAKE_PROGRAM="$MingwBin\mingw32-make.exe" `
            -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"
            
          cmake --build build --config Release

          # 4. Деплой
          New-Item -ItemType Directory -Path dist -Force
          $exeFile = Get-ChildItem -Path build -Filter "*.exe" -Recurse | Select-Object -First 1
          if ($exeFile) {
              Copy-Item $exeFile.FullName -Destination dist\
              windeployqt --dir dist "dist\$($exeFile.Name)"
          } else {
              Write-Error "EXE not found!"
              exit 1
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PathFinder-Windows-Package
          path: dist/
